/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LEFT_PWM.h"
#include "Clock_1.h"
#include "IR_FL1_aliases.h"
#include "IR_FL1.h"
#include "IR_FR2_aliases.h"
#include "IR_FR2.h"
#include "LEFT_MOTOR_CONTROL_aliases.h"
#include "LEFT_MOTOR_CONTROL.h"
#include "Right_MOTOR_CONTROL_aliases.h"
#include "Right_MOTOR_CONTROL.h"
#include "BSTARTGOMB_aliases.h"
#include "BSTARTGOMB.h"
#include "RIGHT_PWM.h"
#include "LEFT_MOTOR_DIR_aliases.h"
#include "LEFT_MOTOR_DIR.h"
#include "RIGHT_MOTOR_DIR_aliases.h"
#include "RIGHT_MOTOR_DIR.h"
#include "BSTOPGOMB_aliases.h"
#include "BSTOPGOMB.h"
#include "BLED3_aliases.h"
#include "BLED3.h"
#include "ADC_pot.h"
#include "LCD.h"
#include "IR_FRA_aliases.h"
#include "IR_FRA.h"
#include "ADC_SARANAL.h"
#include "IR_FFA_aliases.h"
#include "IR_FFA.h"
#include "IR_FLA_aliases.h"
#include "IR_FLA.h"
#include "IR_BRA_aliases.h"
#include "IR_BRA.h"
#include "IR_BBA_aliases.h"
#include "IR_BBA.h"
#include "IR_BLA_aliases.h"
#include "IR_BLA.h"
#include "poti_aliases.h"
#include "poti.h"
#include "ADC_pot_IRQ.h"
#include "ADC_pot_theACLK.h"
#include "ADC_pot_Bypass_aliases.h"
#include "ADC_pot_Bypass.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_SARANAL_SAR.h"
#include "ADC_SARANAL_IntClock.h"
#include "ADC_SARANAL_TempBuf_dma.h"
#include "ADC_SARANAL_FinalBuf_dma.h"
#include "ADC_SARANAL_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

